import type {
  ActivityLog,
  BackupRecord,
  DistribusiHalqah,
  EvaluasiTerbaru,
  HalqahCapaian,
  MasterSantri,
  Predikat,
  PresensiRow,
  RiwayatEvaluasi,
  SantriPerhatian,
  TasmiRecord,
  TargetKurikulum,
  UserAccount,
} from "./types";

export const HALQAH_OPTIONS = [
  "Al-Fatih",
  "Al-Baqarah",
  "An-Nahl",
  "Maryam",
  "Yasin",
  "Thaha",
];

export const CAPAIAN_HALQAH: HalqahCapaian[] = [
  { name: "Al-Fatih", value: 85 },
  { name: "Maryam", value: 91 },
  { name: "Thaha", value: 76 },
  { name: "Al-Baqarah", value: 72 },
  { name: "An-Nahl", value: 64 },
  { name: "Yasin", value: 58 },
];

export const DISTRIBUSI_HALQAH: DistribusiHalqah[] = [
  { name: "Al-Fatih", total: 52, percent: 21, color: "#0e7c5a" },
  { name: "Al-Baqarah", total: 48, percent: 20, color: "#2aa876" },
  { name: "An-Nahl", total: 45, percent: 18, color: "#e9b949" },
  { name: "Maryam", total: 40, percent: 16, color: "#3b82f6" },
  { name: "Yasin", total: 35, percent: 14, color: "#8b5cf6" },
  { name: "Thaha", total: 25, percent: 10, color: "#e05252" },
];

export const SANTRI_PERLU_PERHATIAN: SantriPerhatian[] = [
  {
    nis: "2401",
    nama: "Abdurrahman Hakim",
    halqah: "Al-Fatih",
    tingkat: 3,
    status: "Recovery",
    kendala: "Hafalan terbata-bata",
    target: "Juz 30",
  },
  {
    nis: "2407",
    nama: "Zaid Abdullah",
    halqah: "An-Nahl",
    tingkat: 2,
    status: "Sedang",
    kendala: "Kurang fokus saat setoran",
    target: "Juz 29",
  },
  {
    nis: "2318",
    nama: "Fatih Al-Ghifari",
    halqah: "Yasin",
    tingkat: 4,
    status: "Recovery",
    kendala: "Sering izin tidak masuk",
    target: "Juz 28",
  },
  {
    nis: "2412",
    nama: "Ibrahim Musa",
    halqah: "Al-Baqarah",
    tingkat: 1,
    status: "Sedang",
    kendala: "Adaptasi jadwal baru",
    target: "Juz 30",
  },
  {
    nis: "2305",
    nama: "Umar Sayyid",
    halqah: "Maryam",
    tingkat: 3,
    status: "Sedang",
    kendala: "Target pekanan tertunda",
    target: "Juz 27",
  },
];

export const PRESENSI_TERBARU: PresensiRow[] = [
  {
    tanggal: "25/08/2026",
    jam: "18:12",
    nama: "Ust. Ali Ridho",
    halqah: "Yasin",
    sesi: "Maghrib",
    status: "Hadir",
    jarak: "310 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "18:31",
    nama: "Ust. Syafiq",
    halqah: "Al-Baqarah",
    sesi: "Maghrib",
    status: "Hadir",
    jarak: "480 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "04:52",
    nama: "Ust. Hasan Basri",
    halqah: "Al-Fatih",
    sesi: "Subuh",
    status: "Hadir",
    jarak: "120 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "04:47",
    nama: "Ustzh. Maryam S.",
    halqah: "An-Nahl",
    sesi: "Subuh",
    status: "Hadir",
    jarak: "85 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "—",
    nama: "Ustzh. Khadijah",
    halqah: "Thaha",
    sesi: "Subuh",
    status: "Izin",
    jarak: "—",
    keterangan: "Acara keluarga",
  },
];

export const RIWAYAT_PRESENSI: PresensiRow[] = [
  {
    tanggal: "25/08/2026",
    jam: "18:12",
    nama: "Ust. Ali Ridho",
    halqah: "Yasin",
    sesi: "Maghrib",
    status: "Hadir",
    jarak: "310 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "18:31",
    nama: "Ust. Syafiq",
    halqah: "Al-Baqarah",
    sesi: "Maghrib",
    status: "Hadir",
    jarak: "480 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "04:52",
    nama: "Ust. Hasan Basri",
    halqah: "Al-Fatih",
    sesi: "Subuh",
    status: "Hadir",
    jarak: "120 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "04:47",
    nama: "Ustzh. Maryam S.",
    halqah: "An-Nahl",
    sesi: "Subuh",
    status: "Hadir",
    jarak: "85 m",
    valid: true,
  },
  {
    tanggal: "25/08/2026",
    jam: "—",
    nama: "Ustzh. Khadijah",
    halqah: "Thaha",
    sesi: "Subuh",
    status: "Izin",
    jarak: "—",
    keterangan: "Acara keluarga",
  },
  {
    tanggal: "24/08/2026",
    jam: "18:20",
    nama: "Ust. Hasan Basri",
    halqah: "Al-Fatih",
    sesi: "Maghrib",
    status: "Hadir",
    jarak: "96 m",
    valid: true,
    override: true,
  },
  {
    tanggal: "24/08/2026",
    jam: "—",
    nama: "Ust. Ridwan",
    halqah: "Maryam",
    sesi: "Subuh",
    status: "Sakit",
    jarak: "—",
    keterangan: "Surat sakit terlampir",
  },
];

export const MASTER_SANTRI: MasterSantri[] = [
  {
    nis: "2401",
    nama: "Abdurrahman Hakim",
    jenisKelamin: "Laki-laki",
    halqah: "Al-Fatih",
    tingkat: 3,
    aktif: true,
  },
  {
    nis: "2402",
    nama: "Aisyah Rahmadani",
    jenisKelamin: "Perempuan",
    halqah: "Al-Fatih",
    tingkat: 2,
    aktif: true,
  },
  {
    nis: "2407",
    nama: "Zaid Abdullah",
    jenisKelamin: "Laki-laki",
    halqah: "An-Nahl",
    tingkat: 2,
    aktif: true,
  },
  {
    nis: "2318",
    nama: "Fatih Al-Ghifari",
    jenisKelamin: "Laki-laki",
    halqah: "Yasin",
    tingkat: 4,
    aktif: true,
  },
  {
    nis: "2412",
    nama: "Ibrahim Musa",
    jenisKelamin: "Laki-laki",
    halqah: "Al-Baqarah",
    tingkat: 1,
    aktif: true,
  },
  {
    nis: "2305",
    nama: "Umar Sayyid",
    jenisKelamin: "Laki-laki",
    halqah: "Maryam",
    tingkat: 3,
    aktif: true,
  },
  {
    nis: "2311",
    nama: "Khadijah Az-Zahra",
    jenisKelamin: "Perempuan",
    halqah: "Thaha",
    tingkat: 5,
    aktif: false,
  },
  {
    nis: "2419",
    nama: "Yusuf Al-Qardhawi",
    jenisKelamin: "Laki-laki",
    halqah: "Thaha",
    tingkat: 1,
    aktif: true,
  },
];

export const RIWAYAT_EVALUASI: RiwayatEvaluasi[] = [
  {
    tanggal: "25/08/2026",
    nama: "Abdurrahman Hakim",
    halqah: "Al-Fatih",
    tingkat: 3,
    status: "Recovery",
    kendala: "Hafalan terbata-bata",
    target: "Juz 30",
    oleh: "Ust. Hasan Basri",
  },
  {
    tanggal: "25/08/2026",
    nama: "Aisyah Rahmadani",
    halqah: "Al-Fatih",
    tingkat: 2,
    status: "Tuntas",
    kendala: "—",
    target: "Juz 29",
    oleh: "Ust. Hasan Basri",
  },
  {
    tanggal: "24/08/2026",
    nama: "Zaid Abdullah",
    halqah: "An-Nahl",
    tingkat: 2,
    status: "Sedang",
    kendala: "Kurang fokus saat setoran",
    target: "Juz 29",
    oleh: "Ustzh. Maryam S.",
  },
  {
    tanggal: "24/08/2026",
    nama: "Umar Sayyid",
    halqah: "Maryam",
    tingkat: 3,
    status: "Tuntas",
    kendala: "—",
    target: "Juz 27",
    oleh: "Ustzh. Halimah",
  },
  {
    tanggal: "24/08/2026",
    nama: "Ibrahim Musa",
    halqah: "Al-Baqarah",
    tingkat: 1,
    status: "Sedang",
    kendala: "Target pekanan tertunda",
    target: "Juz 30",
    oleh: "Ust. Syafiq",
  },
  {
    tanggal: "23/08/2026",
    nama: "Fatih Al-Ghifari",
    halqah: "Yasin",
    tingkat: 4,
    status: "Recovery",
    kendala: "Sering izin tidak masuk",
    target: "Juz 28",
    oleh: "Ust. Ali Ridho",
  },
];

export const EVALUASI_TERBARU: EvaluasiTerbaru[] = [
  {
    tanggal: "25/08/2026",
    nama: "Abdurrahman Hakim",
    sesi: "Maghrib",
    status: "Recovery",
    catatan: "Perlu pendampingan muroja'ah harian",
    oleh: "Ust. Hasan Basri",
  },
  {
    tanggal: "25/08/2026",
    nama: "Aisyah Rahmadani",
    sesi: "Subuh",
    status: "Tuntas",
    catatan: "Setoran lancar, tajwid baik",
    oleh: "Ust. Hasan Basri",
  },
  {
    tanggal: "24/08/2026",
    nama: "Yusuf Al-Qardhawi",
    sesi: "Maghrib",
    status: "Tuntas",
    catatan: "Hafal baru 0.5 halaman",
    oleh: "Ust. Hasan Basri",
  },
  {
    tanggal: "24/08/2026",
    nama: "Aisyah Rahmadani",
    sesi: "Subuh",
    status: "Sedang",
    catatan: "Muroja'ah tertunda 1 hari",
    oleh: "Ust. Hasan Basri",
  },
  {
    tanggal: "23/08/2026",
    nama: "Abdurrahman Hakim",
    sesi: "Subuh",
    status: "Sedang",
    catatan: "Masih repair surat An-Naba",
    oleh: "Ust. Hasan Basri",
  },
];

export const TARGET_KURIKULUM: TargetKurikulum[] = [
  { tingkat: 1, nama: "Juz 'Amma", detail: "Juz 30 · 37 surat pendek", target: "Juz 30" },
  { tingkat: 2, nama: "Juz Tabarak", detail: "Juz 29 · 39 surat", target: "Juz 29" },
  { tingkat: 3, nama: "Juz Qad Sami'a", detail: "Juz 28 · 9 surat", target: "Juz 28" },
  { tingkat: 4, nama: "Juz Lanjutan", detail: "Juz 27 · Adz-Dzariyat", target: "Juz 27" },
  { tingkat: 5, nama: "Juz Lanjutan", detail: "Juz 26 · Al-Ahqaf", target: "Juz 26" },
  { tingkat: 6, nama: "Juz Lanjutan", detail: "Juz 25 · Fussilat", target: "Juz 25" },
];

export const TASMI_RECORDS: TasmiRecord[] = [
  {
    tanggal: "21/08/2026",
    nama: "Aisyah Rahmadani",
    nis: "2402",
    halqah: "Al-Fatih",
    jenis: "Pekanan",
    nilai: 92,
    penguji: "Ust. Hasan Basri",
  },
  {
    tanggal: "21/08/2026",
    nama: "Zaid Abdullah",
    nis: "2407",
    halqah: "An-Nahl",
    jenis: "Pekanan",
    nilai: 84,
    penguji: "Ustzh. Maryam S.",
  },
  {
    tanggal: "21/08/2026",
    nama: "Umar Sayyid",
    nis: "2305",
    halqah: "Maryam",
    jenis: "Pekanan",
    nilai: 76,
    penguji: "Ustzh. Halimah",
  },
  {
    tanggal: "14/08/2026",
    nama: "Abdurrahman Hakim",
    nis: "2401",
    halqah: "Al-Fatih",
    jenis: "Pekanan",
    nilai: 65,
    penguji: "Ust. Hasan Basri",
  },
  {
    tanggal: "30/06/2026",
    nama: "Fatih Al-Ghifari",
    nis: "2318",
    halqah: "Yasin",
    jenis: "Per 3 Bulan",
    nilai: 88,
    penguji: "Ust. Ali Ridho",
  },
  {
    tanggal: "30/06/2026",
    nama: "Khadijah Az-Zahra",
    nis: "2311",
    halqah: "Thaha",
    jenis: "Per 6 Bulan",
    nilai: 95,
    penguji: "Ust. Ridwan",
  },
  {
    tanggal: "14/08/2026",
    nama: "Ibrahim Musa",
    nis: "2412",
    halqah: "Al-Baqarah",
    jenis: "Pekanan",
    nilai: 58,
    penguji: "Ust. Syafiq",
  },
];

export function getPredikat(nilai: number): Predikat {
  if (nilai >= 90) {
    return { range: "90–100", nama: "Mumtaz", lulus: true, arab: "ممتاز", variant: "success" };
  }
  if (nilai >= 80) {
    return { range: "80–89", nama: "Jayyid Jiddan", lulus: true, arab: "جيد جداً", variant: "info" };
  }
  if (nilai >= 70) {
    return { range: "70–79", nama: "Jayyid", lulus: true, arab: "جيد", variant: "warning" };
  }
  return { range: "< 70", nama: "Rasib", lulus: false, arab: "راسب", variant: "danger" };
}

export const PREDIKAT_LIST: Predikat[] = [
  getPredikat(95),
  getPredikat(85),
  getPredikat(75),
  getPredikat(50),
];

export const USERS: UserAccount[] = [
  {
    inisial: "AF",
    nama: "Ahmad Fauzi, S.Pd.",
    email: "admin@bqa.sch.id",
    username: "ahmad.fauzi",
    role: "Admin",
    halqah: "—",
    lembaga: "Yayasan",
    aktif: true,
  },
  {
    inisial: "HB",
    nama: "Ust. Hasan Basri",
    email: "hasan.basri@bqa.sch.id",
    username: "hasan.basri",
    role: "Ustadz",
    halqah: "Al-Fatih",
    lembaga: "Tahfidz",
    aktif: true,
  },
  {
    inisial: "MS",
    nama: "Ustzh. Maryam Shaleha",
    email: "maryam.s@bqa.sch.id",
    username: "maryam.s",
    role: "Ustadzah",
    halqah: "An-Nahl",
    lembaga: "Tahfidz",
    aktif: true,
  },
  {
    inisial: "AR",
    nama: "Ust. Ali Ridho",
    email: "ali.ridho@bqa.sch.id",
    username: "ali.ridho",
    role: "Ustadz",
    halqah: "Yasin",
    lembaga: "Tahfidz",
    aktif: true,
  },
  {
    inisial: "KA",
    nama: "Ustzh. Khadijah",
    email: "khadijah.a@bqa.sch.id",
    username: "khadijah.a",
    role: "Ustadzah",
    halqah: "Thaha",
    lembaga: "Tahfidz",
    aktif: false,
  },
  {
    inisial: "AS",
    nama: "KH. Abdullah Syafiq",
    email: "kepsek@bqa.sch.id",
    username: "kepsek",
    role: "Kepsek",
    halqah: "Semua Halqah",
    lembaga: "—",
    aktif: true,
  },
  {
    inisial: "SY",
    nama: "Ust. Syafiq",
    email: "syafiq.i@bqa.sch.id",
    username: "syafiq.i",
    role: "Ustadz",
    halqah: "Al-Baqarah",
    lembaga: "Tahfidz",
    aktif: true,
  },
];

export const BACKUP_RECORDS: BackupRecord[] = [
  { tanggal: "24/08/2026", jenis: "Excel", ukuran: "1.2 MB", oleh: "Ahmad Fauzi" },
  { tanggal: "17/08/2026", jenis: "Excel", ukuran: "1.1 MB", oleh: "Ahmad Fauzi" },
  { tanggal: "10/08/2026", jenis: "JSON", ukuran: "860 KB", oleh: "Ahmad Fauzi" },
  { tanggal: "03/08/2026", jenis: "Excel", ukuran: "1.0 MB", oleh: "Ahmad Fauzi" },
];

export const ACTIVITY_LOGS: ActivityLog[] = [
  {
    waktu: "25/08/2026 · 18:31",
    user: "Ust. Syafiq",
    aktivitas: "Presensi Maghrib — 480 m dari pesantren",
  },
  {
    waktu: "25/08/2026 · 18:12",
    user: "Ust. Ali Ridho",
    aktivitas: "Presensi Maghrib — 310 m dari pesantren",
  },
  {
    waktu: "25/08/2026 · 17:58",
    user: "Ahmad Fauzi",
    aktivitas: "Override presensi Ust. Hasan Basri (sesi Maghrib)",
  },
  {
    waktu: "25/08/2026 · 06:40",
    user: "Ustzh. Maryam S.",
    aktivitas: "Input evaluasi harian — 12 santri (An-Nahl)",
  },
  {
    waktu: "24/08/2026 · 21:00",
    user: "Ahmad Fauzi",
    aktivitas: "Backup data — Excel (1.2 MB)",
  },
];
